name: Deploy Mobirise Site

on:
  push:
    branches:
      - main  # Replace with your branch name if different

permissions:
  contents: read
  pages: write  # This permission is necessary to deploy to GitHub Pages
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Upload Mobirise Files as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./  # Ensure this points to your Mobirise exported files

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
